# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.ignoreResources }}
  annotations:
    resources.gardener.cloud/ignore: "true"
{{- end }}
  labels:
{{ include "labels" . | indent 4 }}
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      annotations:
        {{- if and .Values.metrics.enableScraping }}
        prometheus.io/scrape: "true"
        prometheus.io/name: 'gardener-extension-shoot-flux'
        # default metrics endpoint in controller-runtime
        prometheus.io/port: "{{ .Values.metricsPort }}"
        {{- end }}
      labels:
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.resources.gardener.cloud/to-all-shoots-kube-apiserver-tcp-443: allowed
{{ include "labels" . | indent 8 }}
    spec:
      priorityClassName: gardener-system-900
      serviceAccountName: {{ include "name" . }}
      containers:
      - name: {{ include "name" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - --extension-max-concurrent-reconciles={{ .Values.controllers.extension.concurrentSyncs }}
        - --healthcheck-max-concurrent-reconciles={{ .Values.controllers.healthcheck.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --heartbeat-namespace={{ .Release.Namespace }}
        - --heartbeat-renew-interval-seconds={{ .Values.controllers.heartbeat.renewIntervalSeconds }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        {{- if .Values.metricsPort }}
        - --metrics-bind-address=:{{ .Values.metricsPort }}
        {{- end }}
        {{- if .Values.healthPort }}
        - --health-bind-address=:{{ .Values.healthPort }}
        {{- end }}
        {{- if .Values.gardener.version }}
        - --gardener-version={{ .Values.gardener.version }}
        {{- end }}
        - --log-level={{ .Values.logLevel | default "info" }}
        - --log-format={{ .Values.logFormat | default "json" }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 5
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
