{{- $namespace := .Release.Namespace }}
{{- range $i, $val := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $val.name }}
  namespace: {{ $namespace }}
type: Opaque
{{- with $val.data }}
data:
{{- . | toYaml | nindent 2 }}
{{- end }}
{{- with $val.stringData }}
stringData:
{{- . | toYaml | nindent 2 }}
{{- end }}
{{ end -}}
