apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig/controller-deployment.yaml

resources:
- controller-registration.yaml

images:
- name: ghcr.io/stackitcloud/gardener-extension-shoot-flux
  newTag: v0.4.0
