apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller-registration.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/resources/0/lifecycle
        value:
          reconcile: AfterWorker
    target:
      kind: ControllerRegistration
      name: shoot-flux
