# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
image: ghcr.io/stackitcloud/gardener-extension-shoot-flux:latest
imagePullPolicy: IfNotPresent

replicaCount: 2

logLevel: info
logFormat: json

resources: {}
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  extension:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  heartbeat:
    renewIntervalSeconds: 30
  ignoreOperationAnnotation: false

disableControllers: []
ignoreResources: false

metricsPort: 8080
healthPort: 8081

## settings for metrics, e.g. scraping by seed-prometheus
##
metrics:
  ## enable metrics scraping
  ##
  enableScraping: true

gardener:
  version: ""
  gardenlet:
    featureGates: {}
  seed:
    provider: local
