name: images

on:
  push:
    tags:
    - "v*"
    branches:
    - "*"
    paths-ignore:
    - "**.md"

jobs:
  images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - run: make init
    - run: make images PUSH=true
