name: go:pre-release

on:
  push:
    tags: 'v*'

jobs:
  create-pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Update VERSION file
      run: |-
          echo "${{ github.ref_name }}" > VERSION
    - name: Create controller-registration.yaml
      run: |-
          vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh shoot-flux charts/gardener-extension-shoot-flux ${{ github.ref_name }} controller-registration.yaml \
          Extension:shoot-flux
          vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh shoot-flux charts/gardener-extension-shoot-flux ${{ github.ref_name }}-rc.${{ github.sha }} rc-controller-registration.yaml \
           Extension:shoot-flux
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        body: |-
          # [gardener-extension-shoot-flux] ${{ github.ref_name }}
        prerelease: true
        files: |-
            controller-registration.yaml
            rc-controller-registration.yaml
  go-pre-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Update VERSION file
      run: |-
          echo "${{ github.ref_name }}-rc.${{ github.sha }}" > VERSION
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/23technologies/gardener-extension-shoot-flux:${{ github.ref_name }}-rc.${{ github.sha }}
