name: verify

on:
  pull_request:
    paths-ignore:
    - "**.md"
  push:
    branches:
    - '*'
    paths-ignore:
    - "**.md"

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: make verify-extended
      run: |
        git config --global user.email "ci@gardener.cloud"
        git config --global user.name "ci"
        make verify-extended
