//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&FluxConfig{}, func(obj interface{}) { SetObjectDefaults_FluxConfig(obj.(*FluxConfig)) })
	return nil
}

func SetObjectDefaults_FluxConfig(in *FluxConfig) {
	SetDefaults_FluxConfig(in)
	if in.Flux != nil {
		SetDefaults_FluxInstallation(in.Flux)
	}
	SetDefaults_Source(&in.Source)
	SetDefaults_Kustomization(&in.Kustomization)
}
